### ISSUE TITLE
Make the game web mobile compatible 

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#362]
I just looked at the game on the safari app on my phone and the mobile version could use some improvement. The main screen where you add players has some components that aren't made with bootstrap so the proportions are off. This could increase the amount of people that will take the user study, as they can do it on their phone.

**Comment by mkshiblu** [comment]
I have an idea on making the game mobile responsive -

![mobile view](https://user-images.githubusercontent.com/15908043/43990167-9e82ce1e-9d79-11e8-81d7-c1b3e31c0593.png)

1. The horizontally stacked partially visible cards in the deck would take less space
2. The true and false paths could be horizontally scrollable in the main area and would show only one row of cards. Each row is scrollable and the user could go through his stacks by clicking left or right arrow.

Since this mobile version is quite different from the larger screen version, a possible disadvantage of this design is that the scrollable true and false path area may not be re-usable in the larger screen version.

**Comment by groadybones** [comment]
relates to #122 also this looks like it pertains to the old UI so I'm gonna close it for now, we can deal with this when we go to address the conversation in the other issue
