### ISSUE TITLE
Show upcoming decisions

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#469]
**Is your feature request related to a problem? Please describe.**
One of the items of feedback that we have received is dissatisfaction with the "randomness" of selecting which path will be executed on a given turn.

**Describe the solution you'd like**
A possible solution is to inform the player of what the upcoming decisions will be. This could help them to plan their future moves.

**Comment by groadybones** [comment]
Had an idea for this last night. Instead of having true/false playing fields they're called then and else. A new class of cards is scattered throughout the deck called conditional cards. These cards will say, "if <some form of conditional>" and the game responds by setting the active playfield according to the current active conditional. Some examples of of conditions that a card could contain:
- if(active instructions > 10)
-if(# of groups < 5)

Pros: 
-gives players slight control over active playfield
-adds another aspect of competition
-follows more closely the principles of a conditional

Cons:
-could be confusing
-might be frustrating for players
-lot of work to implement

**Comment by johnanvik** [comment]
This sounds like something worth pursuing. I'm going to move this idea into its own issue so we can explore it further.

**Comment by groadybones** [comment]
Going to close this cause we're removing the random element of our conditional as described in #481
