### ISSUE TITLE
Move from Shawn's domain

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#53]
@sscullen has been kind enough to let us continue using his domain to run Program Wars, but at some point, we will need to move this to a more permanent location (especially once we start publishing about it).

**Comment by johnanvik** [comment]
A free option looks to be BitBalloon (https://www.bitballoon.com). It looks like Travis-CI can deploy to it.

**Comment by JaceRiehl** [comment]
Firebase may be a good option if we can't host it at the University. It looks like it's free for what we would use it for, travis CI can deploy to it, and it's backed by Google.

**Comment by sscullen** [comment]
AFAIK, Firebase is a good option for maintaining application state (its a real time database) which would be good fit for networked multiplayer features. For the hosting of web page, with git push to deploy support like the setup we have now, the easiest would be a linux VM or container that could be set up to mirror the setup we have now, it would be the most seamless transition.

What we could do is look at free hosting such as github pages. Since we don't have an API and all work is done client side, I think you could set it up with github pages (https://docs.travis-ci.com/user/deployment/pages/) and then add Firebase support to have a shared application state among different clients, with Firebase acting as the server-side portion of the application. 

Sorry for the delay, hope this helps!

**Comment by sscullen** [comment]
Sorry, didn't realize Firebase offered hosting of webapps with a domain and everything, thought it was limited to just the NoSQL database hosting. That does look like a good option.
