### ISSUE TITLE
Add a background image to opening page

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#86]
Currently, there is a gray background, which is bland/boring. Needs to be more interesting.

**Comment by vincentcote87** [comment]
pull request #90 might address this issue, I have added a bright colour to the background on the initial game setup page. Maybe a random colour generator could be interesting so that it is not always the same colour. 

Changing the background colour to an image shouldn't be a problem either, I thought maybe a screenshot of some code could look interesting?

**Comment by johnanvik** [comment]
The code image is a nice idea.

**Comment by vincentcote87** [comment]
Here is an example of what I had in mind, I just put down "Hello, World!" programs in different programming languages so that the image doesn't focus on a single programming language. If you like it and want it in lets make sure we fact check the code I put in, other than the C++ I just took them off the internet since I am not familiar with all the languages. 
![screen shot 2017-06-13 at 9 04 52 am](https://user-images.githubusercontent.com/19965014/27089481-b07c8ba6-5017-11e7-965d-9531a80fc163.png)

**Comment by vincentcote87** [comment]
Add the different concepts of the game to the code (ei. loops and variables). Also wrap the code to fill up more of the page.
